### ISSUE TITLE
Error en la documentación (setSenderID)

### ISSUE THREAD

**Issue by anckorweb** [descom-es/php-sms#12]
He visto en la documentacion que el método **setSenderID()** intenta salir desde **$sms** y ese método pertenece a **$message**. Por si lo pueden corregir y así evitar confusiones ;)

Incorrecto:
`$sms->setSenderID('replace_by_sender_of_message');`

Correcto:
`$message->setSenderID('replace_by_sender_of_message');`

**Comment by cesargb** [comment]
Hola, efectivamente la documentación está mal, vamos a corregirlo lo antes posible.

Muchas gracias @anckorweb
