### ISSUE TITLE
Php 8.2 composer

### ISSUE THREAD

**Issue by anckorweb** [descom-es/php-sms#18]
Hello.

When I try to install DescomSms through composer, I get an error:

Package descom/sms-php has requirements incompatible with your PHP version, PHP
extensions and Composer version:
- descom/sms-php v1.2.0 requires php ^5.6|^7.0 which does not match your installed version 8.2.2.

Do you plan to fix this error?
Thank you.

**Comment by vgarciaf** [comment]
PHP requirement is now `~8.1` on release `v1.3.0`
